// Package server provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.1-0.20260318123712-00a90b7a03f4 DO NOT EDIT.
package server

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

// Defines values for ServiceType.
const (
	Cluster          ServiceType = "cluster"
	Container        ServiceType = "container"
	Database         ServiceType = "database"
	ThreeTierAppDemo ServiceType = "three-tier-app-demo"
	Vm               ServiceType = "vm"
)

// Valid indicates whether the value is a known member of the ServiceType enum.
func (e ServiceType) Valid() bool {
	switch e {
	case Cluster:
		return true
	case Container:
		return true
	case Database:
		return true
	case ThreeTierAppDemo:
		return true
	case Vm:
		return true
	default:
		return false
	}
}

// Access VM access configuration
type Access struct {
	// SshPublicKey SSH public key for VM access.
	// Injected via cloud-init/cloudbase-init by providers.
	//
	// Provider mapping:
	// - KubeVirt: cloud-init userData
	// - AWS: key pair
	// - Azure: SSH public key
	// - GCP: instance metadata
	// - VMware: guest customization
	SshPublicKey         *string                `json:"ssh_public_key,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// CommonFields Common fields included in all service type specifications.
// These provide versioning, extensibility, and provider-specific configuration.
type CommonFields struct {
	// CreateTime Timestamp when the resource was created (RFC 3339)
	CreateTime *time.Time `json:"create_time,omitempty"`

	// Id Unique identifier for the resource.
	Id *string `json:"id,omitempty"`

	// Metadata Resource metadata for identification and governance.
	// Used by all service type specifications.
	Metadata ServiceMetadata `json:"metadata"`

	// Path Resource path or location within the system hierarchy.
	Path *string `json:"path,omitempty"`

	// ProviderHints Optional provider-specific configuration.
	//
	// Allows platform-specific settings without breaking portability.
	// Providers use hints they recognize and ignore unknown hints.
	//
	// Keys are provider identifiers (e.g., kubevirt, vmware, aws).
	// Values are provider-specific configuration objects.
	ProviderHints *ProviderHints `json:"provider_hints,omitempty"`

	// ServiceType Service type identifier.
	// Makes the payload self-describing and enables routing/validation.
	ServiceType ServiceType `json:"service_type"`

	// Status Current status of the resource.
	Status *string `json:"status,omitempty"`

	// StatusMessage Human-readable message providing details about the current status
	StatusMessage *string `json:"status_message,omitempty"`

	// UpdateTime Timestamp when the resource was last updated (RFC 3339)
	UpdateTime *time.Time `json:"update_time,omitempty"`
}

// Disk Virtual disk specification
type Disk struct {
	// Capacity Disk capacity with unit suffix (MB, GB, TB)
	Capacity string `json:"capacity"`

	// Name Disk identifier (unique within VM).
	// The root volume must be named "boot".
	// Additional disks can use names like "data", "log", etc.
	Name                 string                 `json:"name"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// Error RFC 7807 compliant error response
type Error struct {
	// Detail Human-readable explanation specific to this occurrence
	Detail *string `json:"detail,omitempty"`

	// Instance URI reference for this specific error occurrence
	Instance *string `json:"instance,omitempty"`

	// Status HTTP status code
	Status *int `json:"status,omitempty"`

	// Title Short human-readable summary of the problem
	Title string `json:"title"`

	// Type URI reference identifying the error type
	Type string `json:"type"`
}

// GuestOS Guest operating system configuration.
// Providers map the OS type to their image catalog.
type GuestOS struct {
	// Type Operating system identifier.
	//
	// Naming convention: <distro>-<version>
	// Examples:
	// - Linux: rhel-9, ubuntu-22.04, fedora-39, centos-stream-9
	// - Windows: windows-server-2022, windows-11
	//
	// Providers map this to their image catalog:
	// - KubeVirt: Container image or DataVolume
	// - VMware: VM template or content library item
	// - AWS: AMI ID
	// - Azure: Image reference
	Type                 string                 `json:"type"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// Health Health status singleton resource
type Health struct {
	// Path Canonical path of the resource
	Path *string `json:"path,omitempty"`

	// Status Health status
	Status *string `json:"status,omitempty"`
}

// Memory Memory configuration (RAM)
type Memory struct {
	// Size Memory size with unit suffix (MB, GB, TB).
	// Maps to guest memory in all providers.
	Size                 string                 `json:"size"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// ProviderHints Optional provider-specific configuration.
//
// Allows platform-specific settings without breaking portability.
// Providers use hints they recognize and ignore unknown hints.
//
// Keys are provider identifiers (e.g., kubevirt, vmware, aws).
// Values are provider-specific configuration objects.
type ProviderHints map[string]map[string]interface{}

// ServiceMetadata Resource metadata for identification and governance.
// Used by all service type specifications.
type ServiceMetadata struct {
	// Labels Key-value pairs for tagging and filtering.
	// Both keys and values must be strings.
	Labels *map[string]string `json:"labels,omitempty"`

	// Name Resource name identifier.
	// Must be unique within the namespace.
	Name string `json:"name"`
}

// ServiceType Service type identifier.
// Makes the payload self-describing and enables routing/validation.
type ServiceType string

// Storage Storage configuration
type Storage struct {
	// Disks Virtual disk specifications.
	//
	// Requirements:
	// - Must contain at least one disk named "boot" for the root volume
	// - Disk names must be unique within the VM
	//
	// Note: The boot disk requirement is enforced at application level.
	Disks                []Disk                 `json:"disks"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// VM Virtual Machine
type VM struct {
	// Path Resource path identifier
	Path *string `json:"path,omitempty"`

	// Spec Provider-agnostic virtual machine specification.
	//
	// Includes common fields (service_type, metadata, provider_hints)
	// plus VM-specific fields for compute, storage, and operating system.
	//
	// Providers translate this abstract specification to their native format.
	Spec VMSpec `json:"spec"`
}

// VMList Paginated list of VMs
type VMList struct {
	// NextPageToken Token for retrieving the next page of results
	NextPageToken *string `json:"next_page_token,omitempty"`
	Vms           *[]VM   `json:"vms,omitempty"`
}

// VMSpec defines model for VMSpec.
type VMSpec struct {
	// Access VM access configuration
	Access *Access `json:"access,omitempty"`

	// CreateTime Timestamp when the resource was created (RFC 3339)
	CreateTime *time.Time `json:"create_time,omitempty"`

	// GuestOs Guest operating system configuration.
	// Providers map the OS type to their image catalog.
	GuestOs GuestOS `json:"guest_os"`

	// Id Unique identifier for the resource.
	Id *string `json:"id,omitempty"`

	// Memory Memory configuration (RAM)
	Memory Memory `json:"memory"`

	// Metadata Resource metadata for identification and governance.
	// Used by all service type specifications.
	Metadata ServiceMetadata `json:"metadata"`

	// Path Resource path or location within the system hierarchy.
	Path *string `json:"path,omitempty"`

	// ProviderHints Optional provider-specific configuration.
	//
	// Allows platform-specific settings without breaking portability.
	// Providers use hints they recognize and ignore unknown hints.
	//
	// Keys are provider identifiers (e.g., kubevirt, vmware, aws).
	// Values are provider-specific configuration objects.
	ProviderHints *ProviderHints `json:"provider_hints,omitempty"`

	// ServiceType Service type identifier.
	// Makes the payload self-describing and enables routing/validation.
	ServiceType ServiceType `json:"service_type"`

	// Status Current status of the resource.
	Status *string `json:"status,omitempty"`

	// StatusMessage Human-readable message providing details about the current status
	StatusMessage *string `json:"status_message,omitempty"`

	// Storage Storage configuration
	Storage Storage `json:"storage"`

	// UpdateTime Timestamp when the resource was last updated (RFC 3339)
	UpdateTime *time.Time `json:"update_time,omitempty"`

	// Vcpu Virtual CPU configuration
	Vcpu                 Vcpu                   `json:"vcpu"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// Vcpu Virtual CPU configuration
type Vcpu struct {
	// Count Number of virtual CPUs.
	// Maps to vCPU count in all providers.
	Count                int                    `json:"count"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// ListVMsParams defines parameters for ListVMs.
type ListVMsParams struct {
	// MaxPageSize Maximum number of results per page
	MaxPageSize *int `form:"max_page_size,omitempty" json:"max_page_size,omitempty"`

	// PageToken Token for pagination
	PageToken *string `form:"page_token,omitempty" json:"page_token,omitempty"`
}

// CreateVMParams defines parameters for CreateVM.
type CreateVMParams struct {
	// Id Optional VM ID for idempotent creation
	Id *string `form:"id,omitempty" json:"id,omitempty"`
}

// CreateVMJSONRequestBody defines body for CreateVM for application/json ContentType.
type CreateVMJSONRequestBody = VM

// Getter for additional properties for Access. Returns the specified
// element and whether it was found
func (a Access) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Access
func (a *Access) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Access to handle AdditionalProperties
func (a *Access) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["ssh_public_key"]; found {
		err = json.Unmarshal(raw, &a.SshPublicKey)
		if err != nil {
			return fmt.Errorf("error reading 'ssh_public_key': %w", err)
		}
		delete(object, "ssh_public_key")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Access to handle AdditionalProperties
func (a Access) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.SshPublicKey != nil {
		object["ssh_public_key"], err = json.Marshal(a.SshPublicKey)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'ssh_public_key': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for Disk. Returns the specified
// element and whether it was found
func (a Disk) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Disk
func (a *Disk) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Disk to handle AdditionalProperties
func (a *Disk) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["capacity"]; found {
		err = json.Unmarshal(raw, &a.Capacity)
		if err != nil {
			return fmt.Errorf("error reading 'capacity': %w", err)
		}
		delete(object, "capacity")
	}

	if raw, found := object["name"]; found {
		err = json.Unmarshal(raw, &a.Name)
		if err != nil {
			return fmt.Errorf("error reading 'name': %w", err)
		}
		delete(object, "name")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Disk to handle AdditionalProperties
func (a Disk) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["capacity"], err = json.Marshal(a.Capacity)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'capacity': %w", err)
	}

	object["name"], err = json.Marshal(a.Name)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'name': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for GuestOS. Returns the specified
// element and whether it was found
func (a GuestOS) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for GuestOS
func (a *GuestOS) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for GuestOS to handle AdditionalProperties
func (a *GuestOS) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["type"]; found {
		err = json.Unmarshal(raw, &a.Type)
		if err != nil {
			return fmt.Errorf("error reading 'type': %w", err)
		}
		delete(object, "type")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for GuestOS to handle AdditionalProperties
func (a GuestOS) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["type"], err = json.Marshal(a.Type)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'type': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for Memory. Returns the specified
// element and whether it was found
func (a Memory) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Memory
func (a *Memory) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Memory to handle AdditionalProperties
func (a *Memory) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["size"]; found {
		err = json.Unmarshal(raw, &a.Size)
		if err != nil {
			return fmt.Errorf("error reading 'size': %w", err)
		}
		delete(object, "size")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Memory to handle AdditionalProperties
func (a Memory) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["size"], err = json.Marshal(a.Size)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'size': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for Storage. Returns the specified
// element and whether it was found
func (a Storage) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Storage
func (a *Storage) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Storage to handle AdditionalProperties
func (a *Storage) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["disks"]; found {
		err = json.Unmarshal(raw, &a.Disks)
		if err != nil {
			return fmt.Errorf("error reading 'disks': %w", err)
		}
		delete(object, "disks")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Storage to handle AdditionalProperties
func (a Storage) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Disks != nil {
		object["disks"], err = json.Marshal(a.Disks)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'disks': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for VMSpec. Returns the specified
// element and whether it was found
func (a VMSpec) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for VMSpec
func (a *VMSpec) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for VMSpec to handle AdditionalProperties
func (a *VMSpec) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["access"]; found {
		err = json.Unmarshal(raw, &a.Access)
		if err != nil {
			return fmt.Errorf("error reading 'access': %w", err)
		}
		delete(object, "access")
	}

	if raw, found := object["create_time"]; found {
		err = json.Unmarshal(raw, &a.CreateTime)
		if err != nil {
			return fmt.Errorf("error reading 'create_time': %w", err)
		}
		delete(object, "create_time")
	}

	if raw, found := object["guest_os"]; found {
		err = json.Unmarshal(raw, &a.GuestOs)
		if err != nil {
			return fmt.Errorf("error reading 'guest_os': %w", err)
		}
		delete(object, "guest_os")
	}

	if raw, found := object["id"]; found {
		err = json.Unmarshal(raw, &a.Id)
		if err != nil {
			return fmt.Errorf("error reading 'id': %w", err)
		}
		delete(object, "id")
	}

	if raw, found := object["memory"]; found {
		err = json.Unmarshal(raw, &a.Memory)
		if err != nil {
			return fmt.Errorf("error reading 'memory': %w", err)
		}
		delete(object, "memory")
	}

	if raw, found := object["metadata"]; found {
		err = json.Unmarshal(raw, &a.Metadata)
		if err != nil {
			return fmt.Errorf("error reading 'metadata': %w", err)
		}
		delete(object, "metadata")
	}

	if raw, found := object["path"]; found {
		err = json.Unmarshal(raw, &a.Path)
		if err != nil {
			return fmt.Errorf("error reading 'path': %w", err)
		}
		delete(object, "path")
	}

	if raw, found := object["provider_hints"]; found {
		err = json.Unmarshal(raw, &a.ProviderHints)
		if err != nil {
			return fmt.Errorf("error reading 'provider_hints': %w", err)
		}
		delete(object, "provider_hints")
	}

	if raw, found := object["service_type"]; found {
		err = json.Unmarshal(raw, &a.ServiceType)
		if err != nil {
			return fmt.Errorf("error reading 'service_type': %w", err)
		}
		delete(object, "service_type")
	}

	if raw, found := object["status"]; found {
		err = json.Unmarshal(raw, &a.Status)
		if err != nil {
			return fmt.Errorf("error reading 'status': %w", err)
		}
		delete(object, "status")
	}

	if raw, found := object["status_message"]; found {
		err = json.Unmarshal(raw, &a.StatusMessage)
		if err != nil {
			return fmt.Errorf("error reading 'status_message': %w", err)
		}
		delete(object, "status_message")
	}

	if raw, found := object["storage"]; found {
		err = json.Unmarshal(raw, &a.Storage)
		if err != nil {
			return fmt.Errorf("error reading 'storage': %w", err)
		}
		delete(object, "storage")
	}

	if raw, found := object["update_time"]; found {
		err = json.Unmarshal(raw, &a.UpdateTime)
		if err != nil {
			return fmt.Errorf("error reading 'update_time': %w", err)
		}
		delete(object, "update_time")
	}

	if raw, found := object["vcpu"]; found {
		err = json.Unmarshal(raw, &a.Vcpu)
		if err != nil {
			return fmt.Errorf("error reading 'vcpu': %w", err)
		}
		delete(object, "vcpu")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for VMSpec to handle AdditionalProperties
func (a VMSpec) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Access != nil {
		object["access"], err = json.Marshal(a.Access)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'access': %w", err)
		}
	}

	if a.CreateTime != nil {
		object["create_time"], err = json.Marshal(a.CreateTime)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'create_time': %w", err)
		}
	}

	object["guest_os"], err = json.Marshal(a.GuestOs)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'guest_os': %w", err)
	}

	if a.Id != nil {
		object["id"], err = json.Marshal(a.Id)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'id': %w", err)
		}
	}

	object["memory"], err = json.Marshal(a.Memory)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'memory': %w", err)
	}

	object["metadata"], err = json.Marshal(a.Metadata)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'metadata': %w", err)
	}

	if a.Path != nil {
		object["path"], err = json.Marshal(a.Path)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'path': %w", err)
		}
	}

	if a.ProviderHints != nil {
		object["provider_hints"], err = json.Marshal(a.ProviderHints)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'provider_hints': %w", err)
		}
	}

	object["service_type"], err = json.Marshal(a.ServiceType)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'service_type': %w", err)
	}

	if a.Status != nil {
		object["status"], err = json.Marshal(a.Status)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'status': %w", err)
		}
	}

	if a.StatusMessage != nil {
		object["status_message"], err = json.Marshal(a.StatusMessage)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'status_message': %w", err)
		}
	}

	object["storage"], err = json.Marshal(a.Storage)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'storage': %w", err)
	}

	if a.UpdateTime != nil {
		object["update_time"], err = json.Marshal(a.UpdateTime)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'update_time': %w", err)
		}
	}

	object["vcpu"], err = json.Marshal(a.Vcpu)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'vcpu': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for Vcpu. Returns the specified
// element and whether it was found
func (a Vcpu) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Vcpu
func (a *Vcpu) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Vcpu to handle AdditionalProperties
func (a *Vcpu) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["count"]; found {
		err = json.Unmarshal(raw, &a.Count)
		if err != nil {
			return fmt.Errorf("error reading 'count': %w", err)
		}
		delete(object, "count")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Vcpu to handle AdditionalProperties
func (a Vcpu) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["count"], err = json.Marshal(a.Count)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'count': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List all VMs
	// (GET /vms)
	ListVMs(w http.ResponseWriter, r *http.Request, params ListVMsParams)
	// Create a VM
	// (POST /vms)
	CreateVM(w http.ResponseWriter, r *http.Request, params CreateVMParams)
	// Health check
	// (GET /vms/health)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// Delete a VM
	// (DELETE /vms/{vmId})
	DeleteVM(w http.ResponseWriter, r *http.Request, vmId string)
	// Get a VM
	// (GET /vms/{vmId})
	GetVM(w http.ResponseWriter, r *http.Request, vmId string)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// List all VMs
// (GET /vms)
func (_ Unimplemented) ListVMs(w http.ResponseWriter, r *http.Request, params ListVMsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a VM
// (POST /vms)
func (_ Unimplemented) CreateVM(w http.ResponseWriter, r *http.Request, params CreateVMParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Health check
// (GET /vms/health)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a VM
// (DELETE /vms/{vmId})
func (_ Unimplemented) DeleteVM(w http.ResponseWriter, r *http.Request, vmId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a VM
// (GET /vms/{vmId})
func (_ Unimplemented) GetVM(w http.ResponseWriter, r *http.Request, vmId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListVMs operation middleware
func (siw *ServerInterfaceWrapper) ListVMs(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListVMsParams

	// ------------- Optional query parameter "max_page_size" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "max_page_size", r.URL.Query(), &params.MaxPageSize, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "max_page_size", Err: err})
		return
	}

	// ------------- Optional query parameter "page_token" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page_token", r.URL.Query(), &params.PageToken, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page_token", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListVMs(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateVM operation middleware
func (siw *ServerInterfaceWrapper) CreateVM(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateVMParams

	// ------------- Optional query parameter "id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "id", r.URL.Query(), &params.Id, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateVM(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteVM operation middleware
func (siw *ServerInterfaceWrapper) DeleteVM(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "vmId" -------------
	var vmId string

	err = runtime.BindStyledParameterWithOptions("simple", "vmId", chi.URLParam(r, "vmId"), &vmId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "vmId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteVM(w, r, vmId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetVM operation middleware
func (siw *ServerInterfaceWrapper) GetVM(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "vmId" -------------
	var vmId string

	err = runtime.BindStyledParameterWithOptions("simple", "vmId", chi.URLParam(r, "vmId"), &vmId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "vmId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetVM(w, r, vmId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/vms", wrapper.ListVMs)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/vms", wrapper.CreateVM)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/vms/health", wrapper.GetHealth)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/vms/{vmId}", wrapper.DeleteVM)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/vms/{vmId}", wrapper.GetVM)
	})

	return r
}

type ListVMsRequestObject struct {
	Params ListVMsParams
}

type ListVMsResponseObject interface {
	VisitListVMsResponse(w http.ResponseWriter) error
}

type ListVMs200JSONResponse VMList

func (response ListVMs200JSONResponse) VisitListVMsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListVMs400ApplicationProblemPlusJSONResponse Error

func (response ListVMs400ApplicationProblemPlusJSONResponse) VisitListVMsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListVMsdefaultApplicationProblemPlusJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response ListVMsdefaultApplicationProblemPlusJSONResponse) VisitListVMsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type CreateVMRequestObject struct {
	Params CreateVMParams
	Body   *CreateVMJSONRequestBody
}

type CreateVMResponseObject interface {
	VisitCreateVMResponse(w http.ResponseWriter) error
}

type CreateVM201JSONResponse VM

func (response CreateVM201JSONResponse) VisitCreateVMResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateVM400ApplicationProblemPlusJSONResponse Error

func (response CreateVM400ApplicationProblemPlusJSONResponse) VisitCreateVMResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateVM409ApplicationProblemPlusJSONResponse Error

func (response CreateVM409ApplicationProblemPlusJSONResponse) VisitCreateVMResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type CreateVM422ApplicationProblemPlusJSONResponse Error

func (response CreateVM422ApplicationProblemPlusJSONResponse) VisitCreateVMResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type CreateVMdefaultApplicationProblemPlusJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response CreateVMdefaultApplicationProblemPlusJSONResponse) VisitCreateVMResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse Health

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteVMRequestObject struct {
	VmId string `json:"vmId"`
}

type DeleteVMResponseObject interface {
	VisitDeleteVMResponse(w http.ResponseWriter) error
}

type DeleteVM204Response struct {
}

func (response DeleteVM204Response) VisitDeleteVMResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteVM400ApplicationProblemPlusJSONResponse Error

func (response DeleteVM400ApplicationProblemPlusJSONResponse) VisitDeleteVMResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteVM404ApplicationProblemPlusJSONResponse Error

func (response DeleteVM404ApplicationProblemPlusJSONResponse) VisitDeleteVMResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteVMdefaultApplicationProblemPlusJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response DeleteVMdefaultApplicationProblemPlusJSONResponse) VisitDeleteVMResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetVMRequestObject struct {
	VmId string `json:"vmId"`
}

type GetVMResponseObject interface {
	VisitGetVMResponse(w http.ResponseWriter) error
}

type GetVM200JSONResponse VM

func (response GetVM200JSONResponse) VisitGetVMResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetVM400ApplicationProblemPlusJSONResponse Error

func (response GetVM400ApplicationProblemPlusJSONResponse) VisitGetVMResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetVM404ApplicationProblemPlusJSONResponse Error

func (response GetVM404ApplicationProblemPlusJSONResponse) VisitGetVMResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetVMdefaultApplicationProblemPlusJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response GetVMdefaultApplicationProblemPlusJSONResponse) VisitGetVMResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List all VMs
	// (GET /vms)
	ListVMs(ctx context.Context, request ListVMsRequestObject) (ListVMsResponseObject, error)
	// Create a VM
	// (POST /vms)
	CreateVM(ctx context.Context, request CreateVMRequestObject) (CreateVMResponseObject, error)
	// Health check
	// (GET /vms/health)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
	// Delete a VM
	// (DELETE /vms/{vmId})
	DeleteVM(ctx context.Context, request DeleteVMRequestObject) (DeleteVMResponseObject, error)
	// Get a VM
	// (GET /vms/{vmId})
	GetVM(ctx context.Context, request GetVMRequestObject) (GetVMResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListVMs operation middleware
func (sh *strictHandler) ListVMs(w http.ResponseWriter, r *http.Request, params ListVMsParams) {
	var request ListVMsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListVMs(ctx, request.(ListVMsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListVMs")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListVMsResponseObject); ok {
		if err := validResponse.VisitListVMsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateVM operation middleware
func (sh *strictHandler) CreateVM(w http.ResponseWriter, r *http.Request, params CreateVMParams) {
	var request CreateVMRequestObject

	request.Params = params

	var body CreateVMJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateVM(ctx, request.(CreateVMRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateVM")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateVMResponseObject); ok {
		if err := validResponse.VisitCreateVMResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request) {
	var request GetHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteVM operation middleware
func (sh *strictHandler) DeleteVM(w http.ResponseWriter, r *http.Request, vmId string) {
	var request DeleteVMRequestObject

	request.VmId = vmId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteVM(ctx, request.(DeleteVMRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteVM")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteVMResponseObject); ok {
		if err := validResponse.VisitDeleteVMResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetVM operation middleware
func (sh *strictHandler) GetVM(w http.ResponseWriter, r *http.Request, vmId string) {
	var request GetVMRequestObject

	request.VmId = vmId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetVM(ctx, request.(GetVMRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetVM")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetVMResponseObject); ok {
		if err := validResponse.VisitGetVMResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
