// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.1-0.20260318123712-00a90b7a03f4 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xaW3PbuJL+KyjuVB1nD6mr4xzrZcuXTKKZyMnGjqbOjLwuiGxJGIMABwAlKzn671sN",
	"gJQo0pYzeyaVh32TSFwaffn66wa/BLFMMylAGB0MvgQ6XkBK7c+zOAZtf9EkYYZJQfkHJTNQhoEOBkbl",
	"EAYJ6FixDF8Hg2A8ItROI7EUMzbPFbVvwiDbmfkl0Hpxl+VTzuK7e1jjk+o619dviXtP7mFNZlKRcunW",
	"RAzF7xAbSMiSURJzmScRE8y07c8p1WD/kumaZEouWQIKZ03EB/+PpDTLmJgPJiIiP+dTGDNlBjsrkVyD",
	"uqSG4oCzX64HVoyMMmUffM4VDEhVSHzx5uLDgDChDRUxkBQMTfwa49GK4px5DtqQONdGpuyzVc4E1QMP",
	"NM04BANUTQRJ7+XL7ik5Ozs7u+hffaYXXf7r5bB7dfP6JT4bvnbDW61WEAZmndmJRjExDzab8omcopqC",
	"TRhcyDSV4kcGPNF1bbu3ZGZfEyZinieQECYI5ZxoUEsWA8FFic4gZjMWW8lRqTcL0FComSxBaSYFE/OQ",
	"wIMBodmUcWbWIaEiKa0RFctU3aQ1qXtKrIAauDMshbrgNywFbWiakdUCBDELIAq0zFUMZEU1cZMTcvTx",
	"xwvS7/dPX1RU3ev0TqJON+r2b7qdQb8z6HR+DcJgJlVKTTAIEmogsjuHgQKavBd8Xfj9ntLDgCV1+T4J",
	"9kcOhCUgDJsxUNaTd8Vs7Vl/mUZ0Gnd7fVQENQYUrvM/v9Hocyc6vT3yP6LbL53wpLspnr/4rx+eI2Ph",
	"kSjpDwpmwSD4j/YWANo++tvXzuSjYvjGCrOoH/BjoW18TaQiXDrXICtmFsyZRK+1gZQsGCiq4sV6/8zt",
	"TMkkj3FaO9cRUG2sULl5luILp7pbMA9iTx2tgIC3dvAmDLx737l1n6WXGxyKUw01eVM85UqBMMS9J3L2",
	"pMlVLjBgnnNUt+BdClrTeUM8vM1TKiJchk45ApAd58OOiTlJwFDGNaFTmRsrVVyRtSJYaVymiReSCIwN",
	"ztfPkTbPkj8fupxqQ9wKz4rfl4Pjl4P+n47fDY74I2cKkmDwW9UpduLmtgFbL5m+/8osyZTJKScJ0/dV",
	"RK3DH81ozExDisRtSfHahhvJMXPpfDZjD+RodB6SN+chuTmvKq3b6bw530MXhJC/H43O//Xm/F835y9+",
	"CBqsKWiTGa0UO/h2lDvI8+E/Hr1wOYIoKQ1ZSp6nQNJcGzIFgksmZBJMpTSToDURZ6UKrW40ianAVGxH",
	"asLZPZBJYHNqEJJJwOUcf4CJ94MKlzwEof9ZRc+nPcIeP9zao8kTXislVQNI/nhBXv2j84ogonBGhSGA",
	"I9HhMyk01KzuwvRgfMNDxqlweFtmVCOJWTBNZOxCO4aKYtAWf8PD/M3lexvc/pxkmhsbfEKaIlcnTb5Q",
	"UJyGjPdxSBTMwG7ssx3TW+ncwR+RrW3f6na314fjlyevIvjH6TTq9pJ+RI9fnkTHvZOT7nH31XGn09mN",
	"81yxqNw0eBQ3G/R5c/OhQOlYJhVpjjudciUmDMxB4VKGGd5w7uuFVIYsqvbReZpStS4SQKbklENaOfJQ",
	"LClnCRmKLDdNohdp6Sk1+/hbI0DjRk7JHru2ey2MyfSg3U7itOWftmKZFlpnTpSIeVGeq969QPHbOj01",
	"RckbpMDvr78OMu0kgmOowWN6TrFPH4vsrpHhW128v3bE1YYFMEVYiikxpoZyOW9inM0af7+/9Rb0bGlx",
	"RVN8GUuxxOdSDMgk73T6ccK0UdL+hsg98izZPZsIT+a1rUbeMZE/DIhaAI9OQ5JPc2HyqNdrdY5DMoNE",
	"Khr1T0MSgzBSR9oooGl0ilN/YSKRKz0gK/cjwiwGKup1er2wfNjt7lZChaKYfkRDeyXShRSGMgHFKKkI",
	"lkljC+y7hc54RAykGafGDoqlMEgzOJsqDAlmIC1rq7PRkAwvdyqroV279Ll9wmR18zxHbHLAt0B5E5l1",
	"zws80EzMORgpSl5S85RmTnxBhRQsptyT4ir7q5xE3j+f9R2Qt77uobIwDB4iCllUSuZOhPlSo/4WTk23",
	"YZDxXFGOCGIf4V6ldgqp8UHOqSpH7UjgyFTB01uIP0y2/TAUbASpVOuvQwQ3p4oA5Ojj2ehFvdvAPjdE",
	"tF8AXz5Nn1oTMaKZDRBXvqdupq+Pd1sMVaZ18ieI1j4RRdGbnLhaxzyquac1Wlt1H/M8GTtct0/EGedy",
	"pQlGPGaO7VANBnFTWyVj2TFVQO8RLDOpDHX9gQp2I+OzxRxGzpooiOVcoJmoSAibC6mA5OJeyJVw46wA",
	"P8NaE6rKZoTagWhNjqA1b4XkPp/CkikTkmWKQBUSutJo4THlOVTnP3Ja4tS1b+4vAV1ZhRfk6MYp1/Rb",
	"D5yqua0Yi+0bxuXdVjnMyYaDlunD2GULdKhXzd2d/XL98TK9KGQsMyvU4yt2VO5cLkEJlKo1EZ80UsL1",
	"M5pAtYjjdAr8SbesoVxV4p9hHS3RJLbpph2TpPM5ug0KOmPcAE5tTcS5NAtyb60vErJ0hixqDLdB3Vgg",
	"lkxJkYJAirPtQARhIFcCEMdKVzZA06BJ8c01UaltfF3lCSMvVbVKwvxgK5yM1tsD6TpKYBktkTem9OEd",
	"iDlmnZN+GKRMFH+7j9Q6kf/19bXO7eOOdtPIkK53XaR6anoP2lFguuaSJkQDn0Vu+rQwKQgkzZoomSNe",
	"tC0b3ekLgshTlM5qIi54SBDaenBKbRkV81wb+9AsFGDxDyqiWRYlkEo80m6nrYluXxupfGvl+anITzrQ",
	"87YVbV1tjzcDHKx9dIZBR3UM0fqQPz+hhnCgSI0FuCWqRfW24bitv3GRy2LoNlLqPjkeWWYrDQwI1o24",
	"pNtEbYXCAhLETKoYEhSHZhkvIIXDErizHhK+g80520rZWMceuvHd0kZUKbquuapTapOvjkeP63pE4wUT",
	"zyV01Sbn1rP3GrfPrlsPE74M4kOqGo+ucVSNL+DD20PUDoX9skzvWLKp8LtlWnA7T+UqQdJM45apFWI8",
	"ese0qSvvA50zYZt4nKGbzsh4pGuKF/Bg7jI6hzsj70E0tAvxsXVmBUYxWBa1Ls4kmS1FZkiyc26qXBjW",
	"P2W/XgxPhr+/Xo96nzpXN//sv/vl0/H7X4ZmdPPT/WjdXVxdfuq9u/nv9dXv/3y4unzdv7o8W40ufjpt",
	"Qoilc+Nn+fN4tJM2tg7c4KvX3uSU8/ezYPDb0+tWrnM24dNYVdU0LW/1ntrA3/1twsAy3jt5cEZR1dtb",
	"hoLNPzXBc35b35SY+2Tz3Q9DG8RZflD3OGY/POzEUsLt1jvnrGPJ7T7eF0w1onMhtWExWXpgSR2wVHHc",
	"wvjQ3appElcu2452O81hyc9CUr3VeDERGc81GY+2pNSvMLPVtb0tCYk/j7tt2++WtKqFv1FUaFuf2/Kf",
	"TrVRNDZV2bddAUENW9qWXkqNw/S6H3u7fH0r/OLDpwPpM5a5aMCXqzydgsLgX26X0jsl29ItnWOmerpg",
	"O7aJh6VIM7r13t+eKzl56t6ysf3RmXQyC0NjlLpOcH1LhRS0qbybPvswDMKAsxiEtkHhWGZwltF4AaTX",
	"whySK77T0VutVi1qX7ekmrf9XN1+N7x4fXX9Ouq1Oq2FSflOA/OgAMuy7Fh2Kc8WtIuzZQaCZiwYBP1W",
	"p3XsytuFNVDbI+McTFMONbkSmtAyDeyFDIK2d1gphkkwCDCf+FxBFU3BgNIWGffKePqAJiOidASfBUgG",
	"ymYGZB848o8cbNB7fab0waUcW2OH/tMHJ/qM5twEg26nY0m39wn770kPeTxtZS4POs9uEmcn++3Kss/U",
	"b9EL3bWB1Xav0yk8DVx87BCw9u9aiu1nHYfTlc3h1oX3GG5uE8Is56Q0ErrD8ZO7+4b3379OCneL0iDE",
	"OU0s8QTtexXeSt9q/08CHjL33Qn4MWHge/zeXy2+OKc1dO65VnC7CYNMNrGjC/uBAqFEwGo/IvzF2XhE",
	"VoxzZOgWuDAoISHSUfQyin3l4yCtGkhuk/HoUCSV7Z7xiAwvixZBmknbubXfUjzuviw57LbWdOcyWf8b",
	"PdYZagvMmGQ2tRjp/tt3rH33VHxrostQ4etvHiLFdZK7w7G7n3673S+kmHEWGxI5rzULRy1sH4RyrHvW",
	"BB6Ydl9eHPd63062cdlNIPAQQ1Yg2PeGIiUi2HitgMgmtDm2aJw/lmr9tUC8gPjeBvGhTF9Fizdg3hYN",
	"/L8s07wtev/1nvPPewrZPc6ORorbiVIrX5bpMNk4dXAwTd8q2OeE1tj6TMnUfQxTto+qOnEzDyNo/Xsv",
	"f/szHiEV9YJ5ALXNhhI/UfpgH8i+jggcNzQ8Rn7T7wSXhpdE57gNJE6G42+IACP7XcNM5iL5HiO/dM96",
	"5IfNkf4GTIM3T9eEGV2084aXTRH+f3Llv8yBO39xlv4uWOz/h8LhUHCO3ZAB/feahcu6KrhNM9beFqm3",
	"5aQD7d/tB4cpFXRuu9m7/hzU67lKbi19SG9nFZfat5v/DQAA//+UmBbtWi8AAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
