// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xaW3PbuJL+KyjuVB1nD6mr4xzrZcuXTKKZyMnGjqbOjLwuiGxJGIMABwAlKzn671sN",
	"gJQo0pYzeyaVh32TSFwaffn66wa/BLFMMylAGB0MvgQ6XkBK7c+zOAZtf9EkYYZJQfkHJTNQhoEOBkbl",
	"EAYJ6FixDF8Hg2A8ItROI7EUMzbPFbVvwiDbmfkl0Hpxl+VTzuK7e1jjk+o619dviXtP7mFNZlKRcunW",
	"RAzF7xAbSMiSURJzmScRE8y07c8p1WD/kumaZEouWQIKZ03EB/+PpDTLmJgPJiIiP+dTGDNlBjsrkVyD",
	"uqSG4oCzX64HVoyMMmUffM4VDEhVSHzx5uLDgDChDRUxkBQMTfwa49GK4px5DtqQONdGpuyzVc4E1QMP",
	"NM04BANUTQRJ7+XL7ik5Ozs7u+hffaYXXf7r5bB7dfP6JT4bvnbDW61WEAZmndmJRjExDzab8omcopqC",
	"TRhcyDSV4kcGPNF1bbu3ZGZfEyZinieQECYI5ZxoUEsWA8FFic4gZjMWW8lRqTcL0FComSxBaSYFE/OQ",
	"wIMBodmUcWbWIaEiKa0RFctU3aQ1qXtKrIAauDMshbrgNywFbWiakdUCBDELIAq0zFUMZEU1cZMTcvTx",
	"xwvS7/dPX1RU3ev0TqJON+r2b7qdQb8z6HR+DcJgJlVKTTAIEmogsjuHgQKavBd8Xfj9ntLDgCV1+T4J",
	"9kcOhCUgDJsxUNaTd8Vs7Vl/mUZ0Gnd7fVQENQYUrvM/v9Hocyc6vT3yP6LbL53wpLspnr/4rx+eI2Ph",
	"kSjpDwpmwSD4j/YWANo++tvXzuSjYvjGCrOoH/BjoW18TaQiXDrXICtmFsyZRK+1gZQsGCiq4sV6/8zt",
	"TMkkj3FaO9cRUG2sULl5luILp7pbMA9iTx2tgIC3dvAmDLx737l1n6WXGxyKUw01eVM85UqBMMS9J3L2",
	"pMlVLjBgnnNUt+BdClrTeUM8vM1TKiJchk45ApAd58OOiTlJwFDGNaFTmRsrVVyRtSJYaVymiReSCIwN",
	"ztfPkTbPkj8fupxqQ9wKz4rfl4Pjl4P+n47fDY74I2cKkmDwW9UpduLmtgFbL5m+/8osyZTJKScJ0/dV",
	"RK3DH81ozExDisRtSfHahhvJMXPpfDZjD+RodB6SN+chuTmvKq3b6bw530MXhJC/H43O//Xm/F835y9+",
	"CBqsKWiTGa0UO/h2lDvI8+E/Hr1wOYIoKQ1ZSp6nQNJcGzIFgksmZBJMpTSToDURZ6UKrW40ianAVGxH",
	"asLZPZBJYHNqEJJJwOUcf4CJ94MKlzwEof9ZRc+nPcIeP9zao8kTXislVQNI/nhBXv2j84ogonBGhSGA",
	"I9HhMyk01KzuwvRgfMNDxqlweFtmVCOJWTBNZOxCO4aKYtAWf8PD/M3lexvc/pxkmhsbfEKaIlcnTb5Q",
	"UJyGjPdxSBTMwG7ssx3TW+ncwR+RrW3f6na314fjlyevIvjH6TTq9pJ+RI9fnkTHvZOT7nH31XGn09mN",
	"81yxqNw0eBQ3G/R5c/OhQOlYJhVpjjudciUmDMxB4VKGGd5w7uuFVIYsqvbReZpStS4SQKbklENaOfJQ",
	"LClnCRmKLDdNohdp6Sk1+/hbI0DjRk7JHru2ey2MyfSg3U7itOWftmKZFlpnTpSIeVGeq969QPHbOj01",
	"RckbpMDvr78OMu0kgmOowWN6TrFPH4vsrpHhW128v3bE1YYFMEVYiikxpoZyOW9inM0af7+/9Rb0bGlx",
	"RVN8GUuxxOdSDMgk73T6ccK0UdL+hsg98izZPZsIT+a1rUbeMZE/DIhaAI9OQ5JPc2HyqNdrdY5DMoNE",
	"Khr1T0MSgzBSR9oooGl0ilN/YSKRKz0gK/cjwiwGKup1er2wfNjt7lZChaKYfkRDeyXShRSGMgHFKKkI",
	"lkljC+y7hc54RAykGafGDoqlMEgzOJsqDAlmIC1rq7PRkAwvdyqroV279Ll9wmR18zxHbHLAt0B5E5l1",
	"zws80EzMORgpSl5S85RmTnxBhRQsptyT4ir7q5xE3j+f9R2Qt77uobIwDB4iCllUSuZOhPlSo/4WTk23",
	"YZDxXFGOCGIf4V6ldgqp8UHOqSpH7UjgyFTB01uIP0y2/TAUbASpVOuvQwQ3p4oA5Ojj2ehFvdvAPjdE",
	"tF8AXz5Nn1oTMaKZDRBXvqdupq+Pd1sMVaZ18ieI1j4RRdGbnLhaxzyquac1Wlt1H/M8GTtct0/EGedy",
	"pQlGPGaO7VANBnFTWyVj2TFVQO8RLDOpDHX9gQp2I+OzxRxGzpooiOVcoJmoSAibC6mA5OJeyJVw46wA",
	"P8NaE6rKZoTagWhNjqA1b4XkPp/CkikTkmWKQBUSutJo4THlOVTnP3Ja4tS1b+4vAV1ZhRfk6MYp1/Rb",
	"D5yqua0Yi+0bxuXdVjnMyYaDlunD2GULdKhXzd2d/XL98TK9KGQsMyvU4yt2VO5cLkEJlKo1EZ80UsL1",
	"M5pAtYjjdAr8SbesoVxV4p9hHS3RJLbpph2TpPM5ug0KOmPcAE5tTcS5NAtyb60vErJ0hixqDLdB3Vgg",
	"lkxJkYJAirPtQARhIFcCEMdKVzZA06BJ8c01UaltfF3lCSMvVbVKwvxgK5yM1tsD6TpKYBktkTem9OEd",
	"iDlmnZN+GKRMFH+7j9Q6kf/19bXO7eOOdtPIkK53XaR6anoP2lFguuaSJkQDn0Vu+rQwKQgkzZoomSNe",
	"tC0b3ekLgshTlM5qIi54SBDaenBKbRkV81wb+9AsFMCdYaDuaJbdJZBKPNJup62Jbl8bqXxr5fmpyE86",
	"0PO2FW1dbY83AxysfXSGQUd1DNH6kD8/oYZwoEiNBbglqkX1tuG4rb9xkcti6DZS6j45HllmKw0MCNaN",
	"uKTbRG2FwgISxEyqGBIUh2YZLyCFwxK4sx4SvoPNOdtK2VjHHrrx3dJGVCm6rrmqU2qTr45Hj+t6ROMF",
	"E88ldNUm59az9xq3z65bDxO+DOJDqhqPrnFUjS/gw9tD1A6F/bJM71iyqfC7ZVpwO0/lKkHSTOOWqRVi",
	"PHrHtKkr7wOdM2GbeJyhm87IeKRrihfwYO4yOoc7I+9BNLQL8bF1ZgVGMVgWtS7OJJktRWZIsnNuqlwY",
	"1j9lv14MT4a/v16Pep86Vzf/7L/75dPx+1+GZnTz0/1o3V1cXX7qvbv57/XV7/98uLp83b+6PFuNLn46",
	"bUKIpXPjZ/nzeLSTNrYO3OCr197klPP3s2Dw29PrVq5zNuHTWFXVNC1v9Z7awN/9bcLAMt47eXBGUdXb",
	"W4aCzT81wXN+W9+UmPtk890PQxvEWX5Q9zhmPzzsxFLC7dY756xjye0+3hdMNaJzIbVhMVl6YEkdsFRx",
	"3ML40N2qaRJXLtuOdjvNYcnPQlK91XgxERnPNRmPtqTUrzCz1bW9LQmJP4+7bdvvlrSqhb9RVGhbn9vy",
	"n061UTQ2Vdm3XQFBDVvall5KjcP0uh97u3x9K/ziw6cD6TOWuWjAl6s8nYLC4F9ul9I7JdvSLZ1jpnq6",
	"YDu2iYelSDO69d7fnis5eeresrH90Zl0MgtDY5S6TnB9S4UUtKm8mz77MAzCgLMYhLZB4VhmcJbReAGk",
	"18Ickiu+09FbrVYtal+3pJq3/Vzdfje8eH11/TrqtTqthUn5TgPzoADLsuxYdinPFrSLs2UGgmYsGAT9",
	"Vqd17MrbhTVQ2yPjHExTDjW5EprQMg3shQyCtndYKYZJMAgwn/hcQRVNwYDSFhn3ynj6gCYjonQEnwVI",
	"BspmBmQfOPKPHGzQe32m9MGlHFtjh/7TByf6jObcBINup2NJt/cJ++9JD3k8bWUuDzrPbhJnJ/vtyrLP",
	"1G/RC921gdV2r9MpPA1cfOwQsPbvWortZx2H05XN4daF9xhubhPCLOekNBK6w/GTu/uG99+/Tgp3i9Ig",
	"xDlNLPEE7XsV3krfav9PAh4y990J+DFh4Hv83l8tvjinNXTuuVZwuwmDTDaxowv7gQKhRMBqPyL8xdl4",
	"RFaMc2ToFrgwKCEh0lH0Mop95eMgrRpIbpPx6FAkle2e8YgML4sWQZpJ27m131I87r4sOey21nTnMln/",
	"Gz3WGWoLzJhkNrUY6f7bd6x991R8a6LLUOHrbx4ixXWSu8Oxu59+u90vpJhxFhsSOa81C0ctbB+Ecqx7",
	"1gQemHZfXhz3et9OtnHZTSDwEENWINj3hiIlIth4rYDIJrQ5tmicP5Zq/bVAvID43gbxoUxfRYs3YN4W",
	"Dfy/LNO8LXr/9Z7zz3sK2T3OjkaK24lSK1+W6TDZOHVwME3fKtjnhNbY+kzJ1H0MU7aPqjpxMw8jaP17",
	"L3/7Mx4hFfWCeQC1zYYSP1H6YB/Ivo4IHDc0PEZ+0+8El4aXROe4DSROhuNviAAj+13DTOYi+R4jv3TP",
	"euSHzZH+BkyDN0/XhBldtPOGl00R/n9y5b/MgTt/cZb+Lljs/4fC4VBwjt2QAf33moXLuiq4TTPW3hap",
	"t+WkA+3f7QeHKRV0brvZu/4c1Ou5Sm4tfUhvZxWX2reb/w0AAP//it545FovAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
