// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xabXPbOJL+K128qdrklpQl2Uk2+nLll2yimcjJxY6mdkc+F0S2JIxBgAOAeknW//2q",
	"AZISRdqK73ZT+bDfKBBoNBpPdz/d1NcgVmmmJEprgsHXwMQLTJl7PI1jNO6JJQm3XEkmPmqVobYcTTCw",
	"OscwSNDEmmf0OhgE4xEwtwxiJWd8nmvm3oRBtrPya2DM4jbLp4LHt3e4oZG6nKurd+Dfwx1uYKY0VKI7",
	"EzmUv2NsMYElZxALlScRl9weuccpM+h+wnQDmVZLnqCmVRP5sfgFKcsyLueDiYzgl3yKY67tYEcS5Ab1",
	"BbOMJpz+ejVwamSMazfwJdc4gLqS9OLt+ccBcGkskzFCipYlhYzxaMVozTxHYyHOjVUp/+KMMyHz4Jql",
	"mcBgQKaJMOm/eNF7Daenp6fnx5df2HlP/P1i2Lu8fvOCxoZv/PROpxOEgd1kbqHVXM6D+/tqRE3JTMF9",
	"GJyrNFXyrxxFYprW9m9h5l4Dl7HIE0yAS2BCgEG95DECCQWTYcxnPHaak1GvF2iwNDMsURuuJJfzEHBt",
	"URo+5YLbTQhMJtVtRKWYOkw6kyZSSiPS808aZ8Eg+I+jLWaPCsAeXXktR+X0eyfI7Xa74AW6HxNQYuOd",
	"m3wfBsW5b70xv2n3a5pKF6Dxj5xrTILBb3U54fZANy33dMHN3RM9jmubMwEJN3f122mYMmYZi7ltcTfa",
	"FsrXsOJ2ATl5gclnM76GZ6OzEN6ehXB99ryG1V63+/aM9mHWoiZJ//NbN3p98+dno7N/vD37x/XZ85+a",
	"AA0DyVJ8QAueoLR8xlHDs1zyP3J0+nAJ49FzjzfQSllYKpGnCGluLEwRSGQCk2CqlJ0EnYk8rUzobGMg",
	"ZpLc2s00IPgdwiRw/hmEMAmEmtMD2riz55Ekcu+QLPpC53xWPEQ3/1kOPf+vn1pdchcR7vjh9j7akPBG",
	"a6WbNvr013N49ZfuKyAQCs6kBaSZoNFkShps3HqClnHRlPQuT5mMNLKETQUCrjPBpANOBSOwCuyCG1Bx",
	"nGuNMsaaYegu/kSH+ZOPHcANlOeEaW5hxQxIZUu/T9qwUIbLpoafPw1B4wzdxi4HOGUq7fzBH9DtyL01",
	"R73+MZ68ePkqwr+8nka9fnIcsZMXL6OT/suXvZPeq5NutxuEwUzplNlgEOSaR9Wmbfoay2zeEkTfXV9/",
	"BP8SYpXUtDnpditJXFqcoyZRllvRcu6rhdIWFvX7MXmaMr0BNQO7cAF3KjCtHXkol0zwBIYyy22b6mUk",
	"e8zMhf9tuJy7jbyRi9i13WthbWYGR0dJnHaK0U6s0tLq3KsS8UKVbzXvnqMU23o7tXnJW0qnH66eFjLd",
	"IqA5zNIxzcZYTBupqEwIhtiCs8WHK58EnVsg18BTNkeImWVCzduyV7vFP+xvvQ16jqZcspRexkouaVzJ",
	"AUzybvc4TrixWrlnjPxQkXH92EQWxMA4ZvOey3w9AL1AEb0OIZ/m0uZRv9/pnoQww0RpFh2/DiFGaZWJ",
	"jNXI0ug1Lf2Vy0StzABW/iGiLIY66nf7/bAa7PV2WVVpKG4esNAe3TpX0jIusZylNBDlGrvAvkuaxiOw",
	"mGaCWTcpVtKitCD4VJNLcItpxdNOR0MYXuywtKGTXWFuL7Z723wbENsA+A6ZsIuWaODGy3hguJwLtEpS",
	"mFa5jpthOmNtYs6ZVJLHTAC9L51/R8j2JOouIJ1Z8kGKTQn8b49eu/o25R6imGGwjhhmUaWZPxHlS0P2",
	"W3gz3YRBJnLNBEUQN0R7VdYptaaBXDBdzdrRwJOpktp1KP5wdVRMI8VGmCq9eVpE8GvqEQCefTodPW9W",
	"LvxLi0cXAujl4/SpM5EjljkH8aVA6lcWXHu3XKkzrZf/B6K1T0RJ9TYQ16nvg5Z73KINqfsxryBjh2uA",
	"iTwVQq0MkMdT5thONWgpbhpnZJVbmGpkdxQsM6Ut87VGLXYT43P8nzxnAxpjNZd0TVSP8LlUGiGXd1Kt",
	"pJ/nFPgFNwaYrgobvROiDTzDzrwTwl0+xSXXNoRlSoEqBLYydMNjJnKsr3/gtODNtX/dXwO2cgYvydG1",
	"N6497qwF03Mk+5bbt8zLe51qmteNJi3T9dhnCwLUq/ZKcb+OajLQwsWr8tYxs9I8vvRwxp2rJWpJWnUm",
	"8rMhSrj5hoKy4XGCTVE8CstGlKtr/AtuoiVdiSvgjWeSbD4n2JCiMy4s0tLORJ4pu6Bq3rg3S3+RZY3h",
	"N2heFsol10qmKIniZFoleVxUYGolkeJYBWWLLA3aDN9eE1XWptd1njAqtKpXSZQfXIWTMWf4WhRJN1GC",
	"y2hJvDFl6/co55R1Xh6HQcpl+bP3QK0TFU9Pr3VuHgbadStDutqFSP3U7A6Np8BsIxRLwKCYRX75tLxS",
	"lESaDWiVU7w4cmx0p8eAMk9JO2eJuOQhQejqwSlzZVQscmPdoF1oxFvLUd+yLLtNMFV0pK1dnZgGCq+s",
	"0myOT0tFxaID/TNX0TbN9nAzwIe1T/5iCKieIToMFecHZkEgI2os0YuoF9VFCVarv0nIRTl16ylNTI5H",
	"jtkqiwOgupFE+k30VikqIFHOlI4xIXVYlokypAhcovC3R4TvYD/HtVLuHbCHfn6vuiOmNds0oOqN2obV",
	"8ehhW49YvOCySeh40lJqebPs9DgKRjce1bP9U4vWnLfW1u2ksoopjlNulQnqkP7m2vkg6VymtwTGQzc2",
	"Hl3RrP1rcUcrRdwcYpqk99dlesuT+xrdXKYl1SyYZc1n21nlMnXKjEfvubFNO35kcy6ZxQQEJ6+ZwXhk",
	"GjiQuLa3GZvjrVV3KJtirmnY+ZZGqzkuy9KbVkLmKqMZcf5c2Do1x83P2d/Phy+Hv7/ZjPqfu5fXfzt+",
	"/+vnkw+/Du3o+ue70aa3uLz43H9//d+by9//tr68eHN8eXG6Gp3//DpovSeP3G9xr/FoJ4tt/anFda6K",
	"q2dCfJgFg98el1vrVN+Hj4fOuqVZ9cHisQ2Kzxr3YeAI+K06uKJsMlAwqYqLxxYUJYgrt6oU8Gj7uJhG",
	"dxBn+UHb05x9N3ELKw23W++csxnabvbTT0mcIzaXylgew7KIc6mPc/W04rLK0H8wMBDXviM82218hxVd",
	"DKHel38+kZnIDYxHW45cSJi5Yj/NcoshFOfxHxL2mzedeh/CaiaNaxe4bgSbGqtZbOu6b5sUklm+dB3G",
	"lFmfYpo4Lu7l6Z3584+fD2TzWOWyJb5c5unUp4jlVpTZqSCXXnROifPx+vHE5UGeEuvpNVuRe1Dy+jTR",
	"cu/atTPldZaWxaR1k28XHR4oWVz12e304zAIA8FjlMY5hSe9wWnG4gVCv0PpJNdip8G4Wq06zL3uKD0/",
	"Ktaao/fD8zeXV2+ifqfbWdhU7PRTDyqwrKqgZY+JbMF6tFplKFnGg0Fw3Ol2Tny1vXAXVPYXBl+DOdoH",
	"uyfxAuM7h9pDGhT4VXKYBIPgLdp3ZZ+j7OO7ffvdbmlr9AjZYURHvxslt99sDwWNd2WLpFma/+IQUHSY",
	"945DvsDmtSYOTT4qckWrOT6hzbU0wKrEuBdETMMElGGL7Mk0S9GiNi5X7PVZ2JpADLJyjSIvQoba5Uqi",
	"hzTzjxxdGCwQlrK1T8KuCRLu2CzBGcuFDQa9btdVRYWXuF+P+szDiTzzzMD7eps6O3xgV5f9UurmX4iH",
	"gtW04OEqdylylguoLokc5OTR3YsvEn9+mhb+M1eLEmcscZUBmqKZVNzS99r/s8R15v9kgMWcXRch27mI",
	"60FbusgyDW6Id6s2vniukVISA4mrfY8ovmyOR7DiQlAJ5UI5hSlMQPkaqooqRWnqg3zdkfwmrp541JOq",
	"ftx4BMOLsoeTZsq11mOS8jB8HSXfGvhAHeJh7K7yTCWbfyKC/cVtUxel4fuGz/T+6Ts2/vTi7IUJmMp1",
	"xOa7u0z5/c9/dHO7v/5+u58rORM8thB5FNuFJ1+uccUEFYkbwDU3/t8VJ/3+99NtXLV/ANcxZmVE+9Gi",
	"ShUhnP/WgkqRc6m2HSb3PrgItG1/o3DjwBrMfaZV6uLItrNVjx1+5eHY8Ugbg2hpoVgROlwPooocpH2w",
	"77JPjiU19z5p6c2MCiV+EI8cXoDJaRtMvA4n3xH7I/cXjJnKZfIjYr6CaxPzYTu9fIu2Bd3TDXBrys7j",
	"8KKNZf+/oP3dAN39F+erH4Lf/ds1DruGB3pLLij+nVhC2FfMRyzjR9uC9qZadKBzXf2dAFIm2dw14nfx",
	"HTQrnVq9W2HIbFeV3+Nv7v83AAD//z69b6thLAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
